<a href="https://colab.research.google.com/github/harshaayyappan/BYTS-ML/blob/main/numpy(12_10_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = []
a.append([7,8,9])
print(a)

a.extend([1,2,3])
print(a)

a.insert(3,8)
print(a)

[[7, 8, 9]]
[[7, 8, 9], 1, 2, 3]
[[7, 8, 9], 1, 2, 8, 3]


In [ ]:
a = (1,2,3,4,4)
print(a.count(4))
print(a.index(2))

2
1


In [ ]:
c = {1:'harsha',2:'dharsh',3:'dhanush'}
print(c)
c[4] = 'John'
print(c)
c[3] = 'hii'
print(c)

{1: 'harsha', 2: 'dharsh', 3: 'dhanush'}
{1: 'harsha', 2: 'dharsh', 3: 'dhanush', 4: 'John'}
{1: 'harsha', 2: 'dharsh', 3: 'hii', 4: 'John'}


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(a.shape)#provide the dimension of the created array - 1D or 2D like that
print(type(a)) # provide the model
b = np.array([[1,4,5],[6,7,8]])
print(b.shape)
c = np.arange(3,10)#assign the numbers present in the given range to the array
print(c)
o = np.arange(10,50,5)
print(o)#first num is starting , 2nd is for ending and 3rd is for intervels
g = np.linspace(0., 1., num=5)#split the number in the given range
print(g)
k = np.linspace(1,10,num=5)#starting and ending will be same inbetween those, they split
print(k)

[1 2 3]
(3,)
<class 'numpy.ndarray'>
(2, 3)
[3 4 5 6 7 8 9]
[10 15 20 25 30 35 40 45]
[0.   0.25 0.5  0.75 1.  ]
[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
print(np.ones(3))#provide the number of ones given
print(np.zeros(5))
print(np.random.random(3))#generate random numbers
print(np.random.random((3,2)))#provide random numbers in the given dimension
print("for 3 - D ARRAY")
print(np.random.random((4,3,2)))

[1. 1. 1.]
[0. 0. 0. 0. 0.]
[0.65400172 0.85303881 0.60812741]
[[0.55645326 0.42577452]
 [0.31702499 0.76879967]
 [0.80804868 0.01722589]]
for 3 - D ARRAY
[[[0.95321046 0.06378507]
  [0.03867353 0.65901314]
  [0.98568695 0.07790403]]

 [[0.53143174 0.61005916]
  [0.22832552 0.1892883 ]
  [0.10146797 0.47012204]]

 [[0.12900411 0.17657876]
  [0.27477952 0.77277384]
  [0.18997592 0.58541357]]

 [[0.6411989  0.75991261]
  [0.39128193 0.29186877]
  [0.73793131 0.91567342]]]


In [ ]:
o = np.full((2,2),10)
print(o)#fill the 2 - d array with the number given

[[10 10]
 [10 10]]


In [ ]:
h = np.array([1,2,3],dtype = np.float64)
print(h) # change the complete array to the given datatype
i = np.array([1,2,3],dtype = np.complex)
print(i)

[1. 2. 3.]
[1.+0.j 2.+0.j 3.+0.j]


<ipython-input-23-0c65725d37a7>:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  i = np.array([1,2,3],dtype = np.complex)


In [ ]:
#slicing
w = np.array([3,4,5])
print(w[0])#access the index
f = np.array([[1,3,5],[2,4,6]])
print(f[0,1])#access in the 2-D array
print(f[0:2,0])#:is for slicing and , is for next set
i = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x = i[1:3,2:4]
print(x)

3
3
[1 2]
[[ 7  8]
 [11 12]]


In [ ]:
#slicing
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])#2-d array with shape(3,4)
r = a[1,:]
r1 = a[1:2,:]
r2 = a[[1],:]
print(r,r.shape)
print(r1,r1.shape)
print(r2,r2.shape)
print()
print()
c = a[:,1]
c1 = a[:,1:2]
print(c,c.shape)
print()
print(c1,c1.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print(a.shape)
#create an array of indices
b = np.array([0,2,0,1])
#select one element from each row of a string and with array indices
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
[ 1  6  7 11]


In [ ]:
p = np.array([[1,2],[3,4],[5,6]])
bool_idx = (p>2) #if the condition satisfies assign the value as true else assign as false
print(bool_idx)
b = p[p>2] #this can assign the values if the condition is true
print(b)

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [ ]:
n = np.array([1,8,9,-3,2,4,7,9])
print(np.argmax(n))
print(np.argmin(n))
print(np.argsort(a))
print(np.where(n>5)[0])
print(np.where(n >= n[np.argmax(n)])[0])

2
3
[0 1 2]
[1 2 6 7]
[2 7]


In [ ]:
a = [0]
a = np.append(a,[1,2,3,4,3])
print(a)
a = np.delete(a,[2,3,5])#use index to delete
print(a)

[0 1 2 3 4 3]
[0 1 4]


In [ ]:
#sorting-default is quicksort we can also provide all sortings
a = np.array([[1,10],[9,7],[5,6]])
print(a)
print()
a = np.sort(a,axis=0,kind='quicksort')#sort with in that [] itself 1=column 0-row
print(a)

[[ 1 10]
 [ 9  7]
 [ 5  6]]

[[ 1  6]
 [ 5  7]
 [ 9 10]]


In [ ]:
#matrix multiplication

a = np.array([[1,2,3],[3,4]])
b = np.array([[1,2],[3,4]])

v = np.array([9,10])
w = np.array([11,12])

#dot operation can be done in these methods
print(v.dot(w))
print(np.dot(v,w))
print(v @ w)


print(a.shape)
#print(a.reshape(1,1)) - Error

#max,min,sum
#print(np.max(a))
#print(np.min(a))
#print(np.sum(a))




219
219
219
(2,)


<ipython-input-71-c9db99719779>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[1,2,3],[3,4]])


In [ ]:
from re import A
A = np.array([[1,2,3],[3,4]])
b = a.squeeze()
print(b)


[list([1, 2, 3]) list([3, 4])]


<ipython-input-52-872c97f07561>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  A = np.array([[1,2,3],[3,4]])


In [ ]:
#broadcasting - extend and add
print(np.array([3,4,5])+np.array([1]))
print()
print(np.array([[2,3,4],[5,6,7]])+np.array([1,2,3]))

[4 5 6]

[[ 3  5  7]
 [ 6  8 10]]
